### PR TITLE
Fix memory issues with label reuse and use of bitmap label

### LINKED ISSUE #15: Memory allocation failed using adafruit_display_text.label
On the Matrix Display & Matrix portal from Adabox 016 I get an error running the Custom Scrolling Quote Board Matrix Display example from [https://learn.adafruit.com/aio-quote-board-matrix-display].

With a feed set up with quotes:

"Gratitude is the art of seeing a gift in everything" -Unknown (Added on:2020-12-03)
"I see little of more importance to the future of our country & our civilization than full recognition of the place of the artist" -John F. Kennedy (Added on:2021-01-12)
"...save us from succumbing to the tragic temptation of becoming cynical" -Martin Luther King Jr. (Added on:2021-01-17)'

and using two colors, I get the error within a minute or two. The error occurs both when connected to MU and also after unplugging/replugging the display.

In PortalBase __init__.py if I replace

> from adafruit_display_text.label import Label

with

> from adafruit_display_text.bitmap_label import Label

the error no longer occurs.

Circuit Python 6.1.0
Libraries adafruit-circuitpython-bundle-6.x-mpy-20210225

### PR DESCRIPTION
**Pull request by makermelissa**
Fixes #15. Apparently labels were getting recreated rather than just reused. The code was refactored to be a little more efficient as well.

### CODE REVIEW

**Comment by makermelissa** [comment]
Oops, I just noticed a bug in the code where text isn't changing.

**Comment by makermelissa** [comment]
I ended up reverting back to the old code because I was running into the max_glyphs error when longer text was used. I took a different approach and am only recreating the label if the text is longer, otherwise it's being reused. This is a bit more memory efficient as the act of creating the label uses up more memory than the unused space does when the text is shorter.

**Comment by makermelissa** [comment]
Ok, I've been running the quote board using this for about an hour without errors so far.

**Review by FoamyGuy — APPROVED** [review]
This looks good to me thanks for the fixes to use less memory.

I tested these changes successfully on:
```
Adafruit CircuitPython 6.2.0-beta.3-36-g103632f44 on 2021-03-07; Adafruit PyPortal with samd51j20
```
Running the quotes, and Bitcoin price projects from Learn Guides everything is working well..

**Comment by ladyada** [comment]
thanks for testing @FoamyGuy

**Pull request merged**
