### PR TITLE
Change to allow passing in secrets in blinka pyportal

### PR DESCRIPTION
**Pull request by makermelissa**
Tested with current iteration of refactored PyPortal and it works without modification, which is the only one that would have been affected.

### CODE REVIEW

**Review by FoamyGuy — CHANGES_REQUESTED** [review]
I think this `raise` needs to get removed, in order for the code to be able to run in environments without a secrets.py file.
https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/blob/d15a11fe4d6ff7be07f3bc55b4d23fb51c4187b7/adafruit_portalbase/network.py#L48

I tried to test with the adafruit_pyportal libarary, but found that it will need some modifications in order to support the lack of secrets.py file if we want to use it like this.

I ended up testing these changes successfully (after removing the `raise`) using adafruit_blinka_pyportal library from the open refactoring PR

The only other minor potential change I noticed is perhaps we want to make some of the docstring wordings a little bit more generic because a few of them refer specifically to a secrets.py file. But this does not prevent the library from working.

**Comment by jfurcean** [comment]
I think the debugging print statement on line 305 needs to be updated as well.

```python
print("Connecting to AP", secrets["ssid"])
```

should be

```python
print("Connecting to AP", self._secrets["ssid"])
```

**Comment by makermelissa** [comment]
Sounds like good changes. I just pushed those items.

**Review by FoamyGuy — APPROVED** [review]
re-tested successfully after the latest commit. Looks good to me.

Thank you @makermelissa 
Nice catch @jfurcean thank you for looking it over as well!

**Pull request merged**
