### PR TITLE
Fix Setbackground for CP7 and add PinAlarm and TouchAlarm support

### LINKED ISSUE #52: Add PinAlarm Implementation
Somehow due to the timing of the implementation, I think this may have been overlooked and only TimeAlarm was added.

### PR DESCRIPTION
**Pull request by makermelissa**
Fixes #52. If a user uses exit_and_deep_sleep(), it creates a TimeAlarm for backwards compatibility, but also allows for PinAlarm and TouchAlarm.

### CODE REVIEW

**Comment by makermelissa** [comment]
Whoops, guess this became a double PR now. I forgot this wasn't merged yet.

**Comment by makermelissa** [comment]
Fixes #56

**Comment by caternuson** [comment]
I tested this and it does fix #56. Did not test anything w.r.t. #52.

**Review by dhalbert — APPROVED** [review]
Thanks! A number of people are running into the background problem.

**Pull request merged**
